# Aviation Mappings Configuration
# Used for T1/T2 format conversion and standardization

# ICAO Abbreviations for T2 Format
ICAO_ABBREVIATIONS = {
    # Runway designations
    "runway left": "L",
    "runway right": "R", 
    "runway center": "C",
    "runway centre": "C",
    "left": "L",
    "right": "R",
    "center": "C",
    "centre": "C",
    
    # Common runway patterns
    "one eight left": "18L",
    "one eight right": "18R",
    "one eight center": "18C",
    "one eight centre": "18C",
    "zero nine left": "09L",
    "zero nine right": "09R",
    "two seven left": "27L",
    "two seven right": "27R",
    "three six left": "36L",
    "three six right": "36R",
    
    # Flight levels
    "flight level": "FL",
    "fl": "FL",
    
    # Altitudes
    "thousand": "000",
    "hundred": "00",
    
    # Frequencies
    "point": ".",
    "decimal": ".",
    
    # Directions
    "degrees": "°",
    "heading": "HDG",
    
    # Aircraft types
    "boeing": "B",
    "airbus": "A",
    "embraer": "E",
    "bombardier": "CL",
    
    # General aviation
    "november": "N",
    "lima": "L",
    "mike": "M",
    "papa": "P",
    "quebec": "Q",
    "romeo": "R",
    "sierra": "S",
    "tango": "T",
    "uniform": "U",
    "victor": "V",
    "whiskey": "W",
    "x-ray": "X",
    "yankee": "Y",
    "zulu": "Z",
}

# Airline Codes to Names (for T1 conversational format)
AIRLINE_CODES = {
    "AAL": "American",
    "DAL": "Delta", 
    "UAL": "United",
    "SWA": "Southwest",
    "JBU": "JetBlue",
    "ASA": "Alaska",
    "VRD": "Virgin",
    "BAW": "British Airways",
    "DLH": "Lufthansa",
    "AFR": "Air France",
    "KLM": "KLM",
    "QFA": "Qantas",
    "CPA": "Cathay Pacific",
    "SIA": "Singapore",
    "EIN": "Aer Lingus",
    "IBE": "Iberia",
    "UAE": "Emirates",
    "QTR": "Qatar",
    "CCA": "Air China",
    "ACA": "Air Canada",
    "USA": "US Airways",
    "AWE": "America West",
    "TWA": "TWA",
    "NWA": "Northwest",
    "PAA": "Pan Am",
    "COA": "Continental",
    "EAL": "Eastern",
    "MTR": "Metro",
    "CPL": "Chaparral",
    "MEP": "Midex",
    "MID": "Midway",
    "MXA": "Mexicana",
    "UPS": "UPS",
    "FDX": "FedEx",
    "MSE": "Air Shuttle",
    "EEC": "Hustler",
    "TAC": "Thai Airways",
    "GLO": "Gulfstream",
    "HAL": "Hawaiian",
    "WJA": "WestJet",
    "VIR": "Virgin",
    "EZY": "EasyJet",
    "RYR": "Ryanair",
    "NKS": "Spirit",
}

# ATC Position Identifiers
ATC_POSITIONS = {
    "DR": "Departure",
    "DR1": "Departure",
    "DR2": "Departure", 
    "APP": "Approach",
    "TWR": "Tower",
    "GND": "Ground",
    "DEP": "Departure",
    "CTR": "Center",
    "ATIS": "ATIS",
    "FSS": "Flight Service",
    "TRACON": "TRACON",
    "ARTCC": "Center",
}

# Number to Word Mappings (for T1 format)
NUMBERS_TO_WORDS = {
    "0": "zero",
    "1": "one", 
    "2": "two",
    "3": "three",
    "4": "four",
    "5": "five",
    "6": "six",
    "7": "seven",
    "8": "eight",
    "9": "nine",
    "10": "ten",
    "11": "eleven",
    "12": "twelve",
    "13": "thirteen",
    "14": "fourteen",
    "15": "fifteen",
    "16": "sixteen",
    "17": "seventeen",
    "18": "eighteen",
    "19": "nineteen",
    "20": "twenty",
    "30": "thirty",
    "40": "forty",
    "50": "fifty",
    "60": "sixty",
    "70": "seventy",
    "80": "eighty",
    "90": "ninety",
    "100": "one hundred",
    "1000": "one thousand",
    "10000": "ten thousand",
    "100000": "one hundred thousand",
}

# Word to Number Mappings (for T2 format)
WORDS_TO_NUMBERS = {v: k for k, v in NUMBERS_TO_WORDS.items()}

# Special aviation number patterns
AVIATION_NUMBERS = {
    "zero": "0",
    "one": "1",
    "two": "2", 
    "three": "3",
    "four": "4",
    "five": "5",
    "six": "6",
    "seven": "7",
    "eight": "8",
    "nine": "9",
    "niner": "9",
    "tree": "3",
    "fife": "5",
    "oh": "0",
    "hundred": "00",
    "thousand": "000",
}

# Aviation Phraseology Standardization
PHRASEOLOGY_STANDARDS = {
    "affirm": "affirmative",
    "negative": "negative",
    "roger": "roger",
    "wilco": "wilco",
    "standby": "standby",
    "say again": "say again",
    "unable": "unable",
    "emergency": "emergency",
    "mayday": "mayday",
    "pan pan": "pan pan",
    "squawk": "squawk",
    "ident": "ident",
    "contact": "contact",
    "monitor": "monitor",
    "frequency": "frequency",
    "altimeter": "altimeter",
    "visibility": "visibility",
    "ceiling": "ceiling",
    "winds": "winds",
    "runway": "runway",
    "taxiway": "taxiway",
    "gate": "gate",
    "ramp": "ramp",
    "apron": "apron",
    "terminal": "terminal",
    "approach": "approach",
    "departure": "departure",
    "arrival": "arrival",
    "cleared": "cleared",
    "approved": "approved",
    "denied": "denied",
    "hold": "hold",
    "proceed": "proceed",
    "continue": "continue",
    "maintain": "maintain",
    "climb": "climb",
    "descend": "descend",
    "level": "level",
    "turn": "turn",
    "heading": "heading",
    "vector": "vector",
    "direct": "direct",
    "expedite": "expedite",
    "reduce": "reduce",
    "increase": "increase",
    "speed": "speed",
    "airspeed": "airspeed",
}

# Proper Nouns for Capitalization (T1 format)
PROPER_NOUNS = {
    # Airports
    "national": "National", 
    "dulles": "Dulles",
    "reagan": "Reagan",
    "kennedy": "Kennedy",
    "laguardia": "LaGuardia",
    "atlanta": "Atlanta",
    "chicago": "Chicago",
    "o'hare": "O'Hare",
    "midway": "Midway",
    "denver": "Denver",
    "phoenix": "Phoenix",
    "seattle": "Seattle",
    "portland": "Portland",
    "san francisco": "San Francisco",
    "los angeles": "Los Angeles",
    "las vegas": "Las Vegas",
    "miami": "Miami",
    "orlando": "Orlando",
    "boston": "Boston",
    "philadelphia": "Philadelphia",
    "detroit": "Detroit",
    "minneapolis": "Minneapolis",
    "houston": "Houston",
    "dallas": "Dallas",
    "fort worth": "Fort Worth",
    "austin": "Austin",
    "san antonio": "San Antonio",
    
    # States and Cities
    "california": "California",
    "texas": "Texas",
    "florida": "Florida",
    "new york": "New York",
    "illinois": "Illinois",
    "virginia": "Virginia",
    "maryland": "Maryland",
    "georgia": "Georgia",
    "colorado": "Colorado",
    "washington": "Washington",
    "oregon": "Oregon",
    "nevada": "Nevada",
    "arizona": "Arizona",
    "utah": "Utah",
    "pennsylvania": "Pennsylvania",
    "massachusetts": "Massachusetts",
    "michigan": "Michigan",
    "minnesota": "Minnesota",
    "ohio": "Ohio",
    "north carolina": "North Carolina",
    "south carolina": "South Carolina",
    "tennessee": "Tennessee",
    "kentucky": "Kentucky",
    "indiana": "Indiana",
    "missouri": "Missouri",
    "louisiana": "Louisiana",
    "alabama": "Alabama",
    "mississippi": "Mississippi",
    
    # ATC Positions
    "approach": "Approach",
    "departure": "Departure", 
    "tower": "Tower",
    "ground": "Ground",
    "center": "Center",
    "clearance": "Clearance",
    "delivery": "Delivery",
    "radio": "Radio",
    "unicom": "Unicom",
    "multicom": "Multicom",
    
    # Aircraft Types
    "boeing": "Boeing",
    "airbus": "Airbus",
    "embraer": "Embraer",
    "bombardier": "Bombardier",
    "cessna": "Cessna",
    "piper": "Piper",
    "beechcraft": "Beechcraft",
    "cirrus": "Cirrus",
    "diamond": "Diamond",
    "mooney": "Mooney",
    "gulfstream": "Gulfstream",
    "learjet": "Learjet",
    "citation": "Citation",
    "falcon": "Falcon",
    "hawker": "Hawker",
    "king air": "King Air",
}

# Allowed Punctuation for T1 Format
T1_ALLOWED_PUNCTUATION = {",", ".", "?", "!"}

# Standard punctuation to remove/replace
PUNCTUATION_CLEANUP = {
    ";": ",",
    ":": ",",
    " - ": ", ",
    " -- ": ", ",
    "...": ".",
    "..": ".",
    "!!": "!",
    "??": "?",
    ".,": ".",
    ".!": "!",
    ".?": "?",
    "!.": "!",
    "?.": "?",
    "!?": "!",
    "?!": "?",
} 